### ISSUE TITLE
Test LD 3.4.0 compatibility for Topics AutoComplete Lessons Module

### ISSUE THREAD

**Issue by actual-saurabh** [UncannyOwl/Uncanny-Toolkit-for-LearnDash#21]
This module has a fix for LD 3.4.0 compatibility. Please test to make sure that the functionality isn't affected.

- [ ] Test with LD 3.4.0 and confirm.
- [ ] Test with LD 3.3.x and confirm.

**Comment by danielarodaz** [comment]
### **It doesn't work as expected**

- [Course](https://beta.uncannycloud.com/wp-admin/post.php?post=1945&action=edit&currentTab=null)
- [Lesson 2](https://beta.uncannycloud.com/courses/25377-topics-autocomplete-test/lessons/lesson-25377-02/) 

The course I'm using has Lesson 1 with **three topics**. When I complete the **first topic**, it automatically completes the Lesson AND redirects me to Lesson 2 instead of topic 2.

It doesn't look right.

https://user-images.githubusercontent.com/48604005/112021923-8d391c80-8b10-11eb-8a37-446c8bcc8617.mov

Thanks!

**Comment by danielarodaz** [comment]
### **It works as expected in LD 3.4.0**
When I complete the third topic, it automatically completes the Lesson 1 and redirects me to Lesson 2.
